### PR TITLE
Disable delete test

### LINKED ISSUE #507: Disable deleting tests which are scheduled for runs
**Describe the bug**
It's possible to delete the test when it's scheduled to run in the future.
**To Reproduce**
1. Create test
2. Run the test with Cron expression
3. Delete test
4. Test deleted successfully

### PR DESCRIPTION
**Pull request by zer0link**
| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     |✔                                                                       |

Related issues: #507 
Closes #507 

Further  information:

Show error when trying to delete test with scheduled jobs

### CODE REVIEW

File: src/jobs/models/database/sequelize/sequelizeConnector.js [hunk 1]
```diff
@@ -175,6 +176,22 @@ async function updateJob(jobId, jobInfo) {
     return updatedJob;
 }
 
+async function getJobBasedOnTestId(testId){
+    const job = client.model('job');
+    console.log('testid = '+testId)
+    let options = {
+        attributes: { exclude: ['updated_at', 'created_at'] }
+    };
+    if (testId) {
```
Comment (enudler) [inline src/jobs/models/database/sequelize/sequelizeConnector.js:185]: this function has to get testId,
no need for the ip

File: src/jobs/models/database/sequelize/sequelizeConnector.js [hunk 2]
```diff
@@ -175,6 +176,22 @@ async function updateJob(jobId, jobInfo) {
     return updatedJob;
 }
 
+async function getJobBasedOnTestId(testId){
+    const job = client.model('job');
+    console.log('testid = '+testId)
```
Comment (enudler) [inline src/jobs/models/database/sequelize/sequelizeConnector.js:181]: please remove console.log

File: src/jobs/models/jobManager.js [hunk 3]
```diff
@@ -175,6 +175,20 @@ module.exports.updateJob = async (jobId, jobConfig) => {
     logger.info('Job updated successfully to database');
 };
 
+module.exports.getJobBasedOnTestId = async (testId) => {
+    try {
+        const jobs = await databaseConnector.getJobBasedOnTestId(testId);
+        logger.info('Got job from database successfully');
```
Comment (enudler) [inline src/jobs/models/jobManager.js:181]: no need for this log.

File: src/tests/controllers/testsController.js [hunk 4]
```diff
@@ -49,8 +50,15 @@ async function getTest(req, res, next) {
...
     try {
-        await manager.deleteTest(req.params.test_id, req.body);
-        return res.status(200).json();
+        const testsJobs = await jobManager.getJobBasedOnTestId(req.params.test_id);
+        if (testsJobs.length === 0) {
+            await manager.deleteTest(req.params.test_id, req.body);
+            return res.status(200).json();
+        } else {
+            let error = 'Please delete all scheduled jobs for the test before deleting the test';
+            return res.status(500).json({message:error});
```
Comment (enudler) [inline src/tests/controllers/testsController.js:59]: return 409 instead of 500 
please change let to const

File: src/tests/controllers/testsController.js [hunk 5]
```diff
@@ -49,8 +50,15 @@ async function getTest(req, res, next) {
...
+        }
```
Comment (enudler) [inline src/tests/controllers/testsController.js:60]: missing tests (unit tests and integration)

**Comment by enudler** [comment]
Hi @zer0link 
Thank you!
Left my comments

File: src/tests/controllers/testsController.js (hunk 5 above)
Comment (zer0link) [reply src/tests/controllers/testsController.js:60]: Hi, I am pretty new with building unit tests and integration tests, is there any guidelines/ examples I can follow?

Comment (enudler) [reply src/tests/controllers/testsController.js:60]: hi,
yes there many unit tests and integration tests in this project

File: tests/integration-tests/tests/tests-test.js [hunk 6]
```diff
@@ -478,6 +479,33 @@ describe('the tests api', function() {
             });
         });
     });
+    describe('Delete tests', () => {
+        it('try to delete test with scheduled jobs and fail', async () => {
+            const requestBody = simpleTest.test;
+            const createTestResponse = await testsRequestSender.createTest(requestBody, validHeaders);
+            const testId = createTestResponse.body.id;
+
+            const jobsBody = {
```
Comment (enudler) [inline tests/integration-tests/tests/tests-test.js:488]: Hi @zer0link 
according to this test, it's impossible to delete a test which is not scheduled
Blocking delete test should be only for cron tests

**Comment by enudler** [comment]
thanks, @zer0link appreciate this PR very much 
going merge it once pipeline succeeds

**Comment by zer0link** [comment]
Hi, Im facing issue creating non-cron jobs for my test, the api returning status code 500.

**Comment by enudler** [comment]
@zer0link hi. you can remove this test that creates non cron job

**Comment by zer0link** [comment]
Webhook test seems to be failing
